# Workflow that pings melpa.org and stable.melpa.org

name: Ping
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every 5 min. This is the shortest time allowed.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "*/5 * * * *"

jobs:
  pinger:
    runs-on: ubuntu-latest
    steps:
      - name: Ping melpa.org
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://melpa.org
      - name: Ping stable.melpa.org
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://stable.melpa.org
